format_version: v1.0
type: UniqueComponent
attributes: {id: pwm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CH0_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH0_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '133333333'}
  - type: KeyValueSet
    attributes: {id: CH0_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH0_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '133333333'}
  - type: Boolean
    attributes: {id: CH0_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH0_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '133333333'}
  - type: Boolean
    attributes: {id: CH0_IER_CHID}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: CH0_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 1.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH0_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CH1_CDTY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: CH1_CPRD}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: CH1_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Boolean
    attributes: {id: CH1_IER_CHID}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: CH1_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 0 Hz ****'}
  - type: Integer
    attributes: {id: CH2_CDTY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: CH2_CPRD}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: CH2_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Boolean
    attributes: {id: CH2_IER_CHID}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: CH2_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH3_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH3_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '9999999'}
  - type: KeyValueSet
    attributes: {id: CH3_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CH3_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '13333333'}
  - type: Boolean
    attributes: {id: CH3_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH3_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '133333333'}
  - type: Comment
    attributes: {id: CH3_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 10.000000225 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH3_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CLKA_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Integer
    attributes: {id: CLKB_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: pwm}
