format_version: v1.0
type: UniqueComponent
attributes: {id: mcan1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CALCULATED_NOMINAL_BITRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '500'}
  - type: String
    attributes: {id: CALCULATED_NOMINAL_ERRORRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '0.000'}
  - type: Integer
    attributes: {id: FILTERS_STD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: MCAN1_STD_FILTER1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: MCAN1_STD_FILTER1_SFID1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1129'}
  - type: Hex
    attributes: {id: MCAN1_STD_FILTER1_SFID2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1129'}
  - type: Integer
    attributes: {id: MCAN_CORE_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '480000000'}
  - type: Comment
    attributes: {id: MCAN_CORE_CLOCK_INVALID_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: Warning!!! MCAN1 Clock Frequency is too high for required
            Nominal Bit Timing}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: MCAN_NOMINAL_ERRORRATE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: Warning!!! Error 1.159%}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: MCAN_TIME_QUANTA_INVALID_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: Warning!!! Number of Time Quanta is too high for required
            Nominal Bit Timing}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: NBTP_NBRP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '14'}
  - type: Integer
    attributes: {id: NBTP_NSJW}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '16'}
  - type: Integer
    attributes: {id: NBTP_NTSEG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '47'}
  - type: Integer
    attributes: {id: NBTP_NTSEG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '16'}
  - type: Integer
    attributes: {id: NBTP_TOTAL_TIME_QUANTA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '64'}
  - type: String
    attributes: {id: NOMINAL_TIME_QUANTA_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcan1, value: '31.250'}
  - type: File
    attributes: {id: instHeaderFile}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/mcan_11273/templates/plib_mcan_interrupt.h.ftl}
  - type: File
    attributes: {id: sourceFile}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/mcan_11273/templates/plib_mcan_interrupt.c.ftl}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: mcan1}
