format_version: v1.0
type: UniqueComponent
attributes: {id: dbgu}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '144'}
  - type: Integer
    attributes: {id: DBGU_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '266666666'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: dbgu}
